version: '3'

services:
  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure:5
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
  webserver:
    build: .
    restart: on-failure:5
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html
    depends_on:
      - database
  phpmyadmin:
    image: phpmyadmin
    restart: on-failure:5
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
    depends_on:
      - database
